name: 'Setup Environment'
description: 'Sets up JDK and creates necessary files from secrets'
inputs:
  google-services-json:
    required: true
    description: 'JSON string for google-services.json written by the workflow.'
runs:
  using: "composite"
  steps:
    - name: Create files
      shell: bash
      env:
        GOOGLE_SERVICES_JSON: ${{ inputs.google-services-json }}
      run: |
        # Fail fast if secrets are missing
        if [ -z "${GOOGLE_SERVICES_JSON:-}" ]; then
          echo "Missing GOOGLE_SERVICES_JSON" >&2
          exit 1
        fi

        # Ensure directories
        mkdir -p app

        # Safely write files
        printf '%s' "$GOOGLE_SERVICES_JSON" > google-services.json
        printf '%s' "$GOOGLE_SERVICES_JSON" > app/google-services.json

    - name: Set up JDK 23
      uses: actions/setup-java@v5
      with:
        java-version: 23
        distribution: 'zulu'
        cache: 'gradle'
